name: Sync to CNB
on: 
 - push
 - delete

jobs:
  sync-push:
    if: ${{ github.repository == 'Tencent/tdesign-vue-next-starter' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync to CNB Repository
        uses: docker://tencentcom/git-sync
        env:
          PLUGIN_TARGET_URL: "https://cnb.cool/tencent/tdesign/tdesign-vue-next-starter.git"
          PLUGIN_AUTH_TYPE: "https"
          PLUGIN_USERNAME: "cnb"
          PLUGIN_PASSWORD: ${{ secrets.CNB_TOKEN }}
          PLUGIN_FORCE: "true"

  sync-delete-branch:
    if: ${{ github.repository == 'Tencent/tdesign-vue-next-starter' && github.event_name == 'delete' && github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam//tdesign-pr-trigger-action@develop
        with:
          repo: 'tencent/tdesign/tdesign-vue-next-starter'
          token: ${{ secrets.CNB_TOKEN }}
          branch: ${{ github.event.ref }}
          trigger: '/delete-cnb-branch'          
